// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto
#ifndef GRPC_inference_2eproto__INCLUDED
#define GRPC_inference_2eproto__INCLUDED

#include "inference.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace agnos {
namespace inference {

// The core C++ compute engine service
class InferenceEngine final {
 public:
  static constexpr char const* service_full_name() {
    return "agnos.inference.InferenceEngine";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Single inference execution
    virtual ::grpc::Status Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::agnos::inference::PredictResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::PredictResponse>> AsyncPredict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::PredictResponse>>(AsyncPredictRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::PredictResponse>> PrepareAsyncPredict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::PredictResponse>>(PrepareAsyncPredictRaw(context, request, cq));
    }
    // Batch processing for higher throughput
    virtual ::grpc::Status BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::agnos::inference::BatchPredictResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::BatchPredictResponse>> AsyncBatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::BatchPredictResponse>>(AsyncBatchPredictRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::BatchPredictResponse>> PrepareAsyncBatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::BatchPredictResponse>>(PrepareAsyncBatchPredictRaw(context, request, cq));
    }
    // Triggers the engine to read a binary model artifact from disk
    virtual ::grpc::Status LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::agnos::inference::LoadModelResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::LoadModelResponse>> AsyncLoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::LoadModelResponse>>(AsyncLoadModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::LoadModelResponse>> PrepareAsyncLoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::LoadModelResponse>>(PrepareAsyncLoadModelRaw(context, request, cq));
    }
    // Liveness and readiness probe
    virtual ::grpc::Status HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::agnos::inference::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::HealthResponse>> AsyncHealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::HealthResponse>>(AsyncHealthCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::HealthResponse>> PrepareAsyncHealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::HealthResponse>>(PrepareAsyncHealthCheckRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Single inference execution
      virtual void Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Batch processing for higher throughput
      virtual void BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Triggers the engine to read a binary model artifact from disk
      virtual void LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Liveness and readiness probe
      virtual void HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::PredictResponse>* AsyncPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::PredictResponse>* PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::BatchPredictResponse>* AsyncBatchPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::BatchPredictResponse>* PrepareAsyncBatchPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::LoadModelResponse>* AsyncLoadModelRaw(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::LoadModelResponse>* PrepareAsyncLoadModelRaw(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::HealthResponse>* AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::agnos::inference::HealthResponse>* PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::agnos::inference::PredictResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>> AsyncPredict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>>(AsyncPredictRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>> PrepareAsyncPredict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>>(PrepareAsyncPredictRaw(context, request, cq));
    }
    ::grpc::Status BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::agnos::inference::BatchPredictResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>> AsyncBatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>>(AsyncBatchPredictRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>> PrepareAsyncBatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>>(PrepareAsyncBatchPredictRaw(context, request, cq));
    }
    ::grpc::Status LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::agnos::inference::LoadModelResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>> AsyncLoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>>(AsyncLoadModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>> PrepareAsyncLoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>>(PrepareAsyncLoadModelRaw(context, request, cq));
    }
    ::grpc::Status HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::agnos::inference::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>> AsyncHealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>>(AsyncHealthCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>> PrepareAsyncHealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>>(PrepareAsyncHealthCheckRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response, std::function<void(::grpc::Status)>) override;
      void Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response, std::function<void(::grpc::Status)>) override;
      void BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response, std::function<void(::grpc::Status)>) override;
      void LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>* AsyncPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>* PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>* AsyncBatchPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>* PrepareAsyncBatchPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>* AsyncLoadModelRaw(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>* PrepareAsyncLoadModelRaw(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>* AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>* PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Predict_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchPredict_;
    const ::grpc::internal::RpcMethod rpcmethod_LoadModel_;
    const ::grpc::internal::RpcMethod rpcmethod_HealthCheck_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Single inference execution
    virtual ::grpc::Status Predict(::grpc::ServerContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response);
    // Batch processing for higher throughput
    virtual ::grpc::Status BatchPredict(::grpc::ServerContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response);
    // Triggers the engine to read a binary model artifact from disk
    virtual ::grpc::Status LoadModel(::grpc::ServerContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response);
    // Liveness and readiness probe
    virtual ::grpc::Status HealthCheck(::grpc::ServerContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Predict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Predict() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Predict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predict(::grpc::ServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPredict(::grpc::ServerContext* context, ::agnos::inference::PredictRequest* request, ::grpc::ServerAsyncResponseWriter< ::agnos::inference::PredictResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchPredict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BatchPredict() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BatchPredict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchPredict(::grpc::ServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchPredict(::grpc::ServerContext* context, ::agnos::inference::BatchPredictRequest* request, ::grpc::ServerAsyncResponseWriter< ::agnos::inference::BatchPredictResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LoadModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LoadModel() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_LoadModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadModel(::grpc::ServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadModel(::grpc::ServerContext* context, ::agnos::inference::LoadModelRequest* request, ::grpc::ServerAsyncResponseWriter< ::agnos::inference::LoadModelResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_HealthCheck() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealthCheck(::grpc::ServerContext* context, ::agnos::inference::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::agnos::inference::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Predict<WithAsyncMethod_BatchPredict<WithAsyncMethod_LoadModel<WithAsyncMethod_HealthCheck<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Predict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Predict() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response) { return this->Predict(context, request, response); }));}
    void SetMessageAllocatorFor_Predict(
        ::grpc::MessageAllocator< ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Predict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predict(::grpc::ServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Predict(
      ::grpc::CallbackServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BatchPredict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BatchPredict() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response) { return this->BatchPredict(context, request, response); }));}
    void SetMessageAllocatorFor_BatchPredict(
        ::grpc::MessageAllocator< ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_BatchPredict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchPredict(::grpc::ServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BatchPredict(
      ::grpc::CallbackServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LoadModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LoadModel() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response) { return this->LoadModel(context, request, response); }));}
    void SetMessageAllocatorFor_LoadModel(
        ::grpc::MessageAllocator< ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_LoadModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadModel(::grpc::ServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LoadModel(
      ::grpc::CallbackServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_HealthCheck() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response) { return this->HealthCheck(context, request, response); }));}
    void SetMessageAllocatorFor_HealthCheck(
        ::grpc::MessageAllocator< ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HealthCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Predict<WithCallbackMethod_BatchPredict<WithCallbackMethod_LoadModel<WithCallbackMethod_HealthCheck<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Predict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Predict() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Predict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predict(::grpc::ServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchPredict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BatchPredict() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BatchPredict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchPredict(::grpc::ServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LoadModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LoadModel() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_LoadModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadModel(::grpc::ServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_HealthCheck() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Predict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Predict() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Predict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predict(::grpc::ServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPredict(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchPredict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BatchPredict() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BatchPredict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchPredict(::grpc::ServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchPredict(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LoadModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LoadModel() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_LoadModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadModel(::grpc::ServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_HealthCheck() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealthCheck(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Predict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Predict() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Predict(context, request, response); }));
    }
    ~WithRawCallbackMethod_Predict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predict(::grpc::ServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Predict(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BatchPredict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BatchPredict() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BatchPredict(context, request, response); }));
    }
    ~WithRawCallbackMethod_BatchPredict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchPredict(::grpc::ServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BatchPredict(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LoadModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LoadModel() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LoadModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_LoadModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadModel(::grpc::ServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LoadModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_HealthCheck() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->HealthCheck(context, request, response); }));
    }
    ~WithRawCallbackMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HealthCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Predict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Predict() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse>* streamer) {
                       return this->StreamedPredict(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Predict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Predict(::grpc::ServerContext* /*context*/, const ::agnos::inference::PredictRequest* /*request*/, ::agnos::inference::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPredict(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agnos::inference::PredictRequest,::agnos::inference::PredictResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchPredict : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BatchPredict() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse>* streamer) {
                       return this->StreamedBatchPredict(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BatchPredict() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchPredict(::grpc::ServerContext* /*context*/, const ::agnos::inference::BatchPredictRequest* /*request*/, ::agnos::inference::BatchPredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchPredict(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agnos::inference::BatchPredictRequest,::agnos::inference::BatchPredictResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LoadModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LoadModel() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse>* streamer) {
                       return this->StreamedLoadModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LoadModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LoadModel(::grpc::ServerContext* /*context*/, const ::agnos::inference::LoadModelRequest* /*request*/, ::agnos::inference::LoadModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLoadModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agnos::inference::LoadModelRequest,::agnos::inference::LoadModelResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_HealthCheck() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse>* streamer) {
                       return this->StreamedHealthCheck(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::agnos::inference::HealthRequest* /*request*/, ::agnos::inference::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealthCheck(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::agnos::inference::HealthRequest,::agnos::inference::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Predict<WithStreamedUnaryMethod_BatchPredict<WithStreamedUnaryMethod_LoadModel<WithStreamedUnaryMethod_HealthCheck<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Predict<WithStreamedUnaryMethod_BatchPredict<WithStreamedUnaryMethod_LoadModel<WithStreamedUnaryMethod_HealthCheck<Service > > > > StreamedService;
};

}  // namespace inference
}  // namespace agnos


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_inference_2eproto__INCLUDED
