// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace agnos {
namespace inference {

static const char* InferenceEngine_method_names[] = {
  "/agnos.inference.InferenceEngine/Predict",
  "/agnos.inference.InferenceEngine/BatchPredict",
  "/agnos.inference.InferenceEngine/LoadModel",
  "/agnos.inference.InferenceEngine/HealthCheck",
};

std::unique_ptr< InferenceEngine::Stub> InferenceEngine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceEngine::Stub> stub(new InferenceEngine::Stub(channel, options));
  return stub;
}

InferenceEngine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Predict_(InferenceEngine_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchPredict_(InferenceEngine_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LoadModel_(InferenceEngine_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HealthCheck_(InferenceEngine_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InferenceEngine::Stub::Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::agnos::inference::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void InferenceEngine::Stub::async::Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void InferenceEngine::Stub::async::Predict(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>* InferenceEngine::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agnos::inference::PredictResponse, ::agnos::inference::PredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Predict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::PredictResponse>* InferenceEngine::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InferenceEngine::Stub::BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::agnos::inference::BatchPredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchPredict_, context, request, response);
}

void InferenceEngine::Stub::async::BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchPredict_, context, request, response, std::move(f));
}

void InferenceEngine::Stub::async::BatchPredict(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchPredict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>* InferenceEngine::Stub::PrepareAsyncBatchPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agnos::inference::BatchPredictResponse, ::agnos::inference::BatchPredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchPredict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::BatchPredictResponse>* InferenceEngine::Stub::AsyncBatchPredictRaw(::grpc::ClientContext* context, const ::agnos::inference::BatchPredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InferenceEngine::Stub::LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::agnos::inference::LoadModelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadModel_, context, request, response);
}

void InferenceEngine::Stub::async::LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadModel_, context, request, response, std::move(f));
}

void InferenceEngine::Stub::async::LoadModel(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>* InferenceEngine::Stub::PrepareAsyncLoadModelRaw(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agnos::inference::LoadModelResponse, ::agnos::inference::LoadModelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::LoadModelResponse>* InferenceEngine::Stub::AsyncLoadModelRaw(::grpc::ClientContext* context, const ::agnos::inference::LoadModelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InferenceEngine::Stub::HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::agnos::inference::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void InferenceEngine::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void InferenceEngine::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>* InferenceEngine::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::agnos::inference::HealthResponse, ::agnos::inference::HealthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::agnos::inference::HealthResponse>* InferenceEngine::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::agnos::inference::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

InferenceEngine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceEngine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceEngine::Service, ::agnos::inference::PredictRequest, ::agnos::inference::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agnos::inference::PredictRequest* req,
             ::agnos::inference::PredictResponse* resp) {
               return service->Predict(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceEngine_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceEngine::Service, ::agnos::inference::BatchPredictRequest, ::agnos::inference::BatchPredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agnos::inference::BatchPredictRequest* req,
             ::agnos::inference::BatchPredictResponse* resp) {
               return service->BatchPredict(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceEngine_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceEngine::Service, ::agnos::inference::LoadModelRequest, ::agnos::inference::LoadModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agnos::inference::LoadModelRequest* req,
             ::agnos::inference::LoadModelResponse* resp) {
               return service->LoadModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceEngine_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceEngine::Service, ::agnos::inference::HealthRequest, ::agnos::inference::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::agnos::inference::HealthRequest* req,
             ::agnos::inference::HealthResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
}

InferenceEngine::Service::~Service() {
}

::grpc::Status InferenceEngine::Service::Predict(::grpc::ServerContext* context, const ::agnos::inference::PredictRequest* request, ::agnos::inference::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InferenceEngine::Service::BatchPredict(::grpc::ServerContext* context, const ::agnos::inference::BatchPredictRequest* request, ::agnos::inference::BatchPredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InferenceEngine::Service::LoadModel(::grpc::ServerContext* context, const ::agnos::inference::LoadModelRequest* request, ::agnos::inference::LoadModelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InferenceEngine::Service::HealthCheck(::grpc::ServerContext* context, const ::agnos::inference::HealthRequest* request, ::agnos::inference::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace agnos
}  // namespace inference
#include <grpcpp/ports_undef.inc>

