// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: inference.proto

package inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_inference_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7, 0}
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Passed from Go API for request tracking
	InputShape    []int64                `protobuf:"varint,3,rep,packed,name=input_shape,json=inputShape,proto3" json:"input_shape,omitempty"`  // e.g., [1, 28, 28]
	TensorData    []float32              `protobuf:"fixed32,4,rep,packed,name=tensor_data,json=tensorData,proto3" json:"tensor_data,omitempty"` // Flattened input array
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PredictRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PredictRequest) GetInputShape() []int64 {
	if x != nil {
		return x.InputShape
	}
	return nil
}

func (x *PredictRequest) GetTensorData() []float32 {
	if x != nil {
		return x.TensorData
	}
	return nil
}

type PredictResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId     string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Prediction        []float32              `protobuf:"fixed32,2,rep,packed,name=prediction,proto3" json:"prediction,omitempty"`                                  // Flattened output array
	OutputShape       []int64                `protobuf:"varint,3,rep,packed,name=output_shape,json=outputShape,proto3" json:"output_shape,omitempty"`              // Shape of the prediction tensor
	ComputationTimeUs int64                  `protobuf:"varint,4,opt,name=computation_time_us,json=computationTimeUs,proto3" json:"computation_time_us,omitempty"` // Tracked internally by C++ for Prometheus metrics (microseconds)
	ErrorMessage      string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                   // Empty if successful
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PredictResponse) GetPrediction() []float32 {
	if x != nil {
		return x.Prediction
	}
	return nil
}

func (x *PredictResponse) GetOutputShape() []int64 {
	if x != nil {
		return x.OutputShape
	}
	return nil
}

func (x *PredictResponse) GetComputationTimeUs() int64 {
	if x != nil {
		return x.ComputationTimeUs
	}
	return 0
}

func (x *PredictResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BatchPredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*PredictRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictRequest) Reset() {
	*x = BatchPredictRequest{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictRequest) ProtoMessage() {}

func (x *BatchPredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictRequest.ProtoReflect.Descriptor instead.
func (*BatchPredictRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *BatchPredictRequest) GetRequests() []*PredictRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchPredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*PredictResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictResponse) Reset() {
	*x = BatchPredictResponse{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictResponse) ProtoMessage() {}

func (x *BatchPredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictResponse.ProtoReflect.Descriptor instead.
func (*BatchPredictResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *BatchPredictResponse) GetResponses() []*PredictResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ArtifactPath  string                 `protobuf:"bytes,2,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"` // Absolute or relative path to the .agnos binary file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *LoadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LoadModelRequest) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LoadTimeMs    int64                  `protobuf:"varint,3,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LoadModelResponse) GetLoadTimeMs() int64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=agnos.inference.HealthResponse_Status" json:"status,omitempty"`
	ActiveModelsCount int32                  `protobuf:"varint,2,opt,name=active_models_count,json=activeModelsCount,proto3" json:"active_models_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetActiveModelsCount() int32 {
	if x != nil {
		return x.ActiveModelsCount
	}
	return 0
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x0fagnos.inference\"\x94\x01\n" +
	"\x0ePredictRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x1f\n" +
	"\vinput_shape\x18\x03 \x03(\x03R\n" +
	"inputShape\x12\x1f\n" +
	"\vtensor_data\x18\x04 \x03(\x02R\n" +
	"tensorData\"\xd0\x01\n" +
	"\x0fPredictResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1e\n" +
	"\n" +
	"prediction\x18\x02 \x03(\x02R\n" +
	"prediction\x12!\n" +
	"\foutput_shape\x18\x03 \x03(\x03R\voutputShape\x12.\n" +
	"\x13computation_time_us\x18\x04 \x01(\x03R\x11computationTimeUs\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"R\n" +
	"\x13BatchPredictRequest\x12;\n" +
	"\brequests\x18\x01 \x03(\v2\x1f.agnos.inference.PredictRequestR\brequests\"V\n" +
	"\x14BatchPredictResponse\x12>\n" +
	"\tresponses\x18\x01 \x03(\v2 .agnos.inference.PredictResponseR\tresponses\"R\n" +
	"\x10LoadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12#\n" +
	"\rartifact_path\x18\x02 \x01(\tR\fartifactPath\"t\n" +
	"\x11LoadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12 \n" +
	"\fload_time_ms\x18\x03 \x01(\x03R\n" +
	"loadTimeMs\"\x0f\n" +
	"\rHealthRequest\"\xb5\x01\n" +
	"\x0eHealthResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.agnos.inference.HealthResponse.StatusR\x06status\x12.\n" +
	"\x13active_models_count\x18\x02 \x01(\x05R\x11activeModelsCount\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xe0\x02\n" +
	"\x0fInferenceEngine\x12L\n" +
	"\aPredict\x12\x1f.agnos.inference.PredictRequest\x1a .agnos.inference.PredictResponse\x12[\n" +
	"\fBatchPredict\x12$.agnos.inference.BatchPredictRequest\x1a%.agnos.inference.BatchPredictResponse\x12R\n" +
	"\tLoadModel\x12!.agnos.inference.LoadModelRequest\x1a\".agnos.inference.LoadModelResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.agnos.inference.HealthRequest\x1a\x1f.agnos.inference.HealthResponseB\x1dZ\x1bagnos-ml/api/grpc/inferenceb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_inference_proto_goTypes = []any{
	(HealthResponse_Status)(0),   // 0: agnos.inference.HealthResponse.Status
	(*PredictRequest)(nil),       // 1: agnos.inference.PredictRequest
	(*PredictResponse)(nil),      // 2: agnos.inference.PredictResponse
	(*BatchPredictRequest)(nil),  // 3: agnos.inference.BatchPredictRequest
	(*BatchPredictResponse)(nil), // 4: agnos.inference.BatchPredictResponse
	(*LoadModelRequest)(nil),     // 5: agnos.inference.LoadModelRequest
	(*LoadModelResponse)(nil),    // 6: agnos.inference.LoadModelResponse
	(*HealthRequest)(nil),        // 7: agnos.inference.HealthRequest
	(*HealthResponse)(nil),       // 8: agnos.inference.HealthResponse
}
var file_inference_proto_depIdxs = []int32{
	1, // 0: agnos.inference.BatchPredictRequest.requests:type_name -> agnos.inference.PredictRequest
	2, // 1: agnos.inference.BatchPredictResponse.responses:type_name -> agnos.inference.PredictResponse
	0, // 2: agnos.inference.HealthResponse.status:type_name -> agnos.inference.HealthResponse.Status
	1, // 3: agnos.inference.InferenceEngine.Predict:input_type -> agnos.inference.PredictRequest
	3, // 4: agnos.inference.InferenceEngine.BatchPredict:input_type -> agnos.inference.BatchPredictRequest
	5, // 5: agnos.inference.InferenceEngine.LoadModel:input_type -> agnos.inference.LoadModelRequest
	7, // 6: agnos.inference.InferenceEngine.HealthCheck:input_type -> agnos.inference.HealthRequest
	2, // 7: agnos.inference.InferenceEngine.Predict:output_type -> agnos.inference.PredictResponse
	4, // 8: agnos.inference.InferenceEngine.BatchPredict:output_type -> agnos.inference.BatchPredictResponse
	6, // 9: agnos.inference.InferenceEngine.LoadModel:output_type -> agnos.inference.LoadModelResponse
	8, // 10: agnos.inference.InferenceEngine.HealthCheck:output_type -> agnos.inference.HealthResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		EnumInfos:         file_inference_proto_enumTypes,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
